services:
  build:
    build:
      context: .
      dockerfile_inline: |
        FROM ubuntu:latest
        RUN apt -qqq update
        RUN apt -qqq install gpp ruby-kramdown-rfc2629 libxml2-utils make xml2rfc
        WORKDIR /src
    volumes:
      - .:/src
      - ./_site:/src/_site
    command: make pages
